name: lint

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          skip-cache: true

      - name: Run lint
        run: make lint
